services:
  app:  # Místo 'web_app' použij jen 'app'
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - REDIS_HOST=cache
    depends_on:
      - cache

  cache: # Název služby pro Redis
    image: redis:7-alpine
