services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - REDIS_HOST=cache
    depends_on:
      - cache

  cache:
    image: redis:7-alpine
    # Příkaz 'appendonly yes' zajistí, že se data zapisují na disk okamžitě
    command: redis-server --appendonly yes

