version: '3.8'

services:
  herni-app:
    build: .
    container_name: herni_ai_api
    ports:
      - [cite_start]"8081:8081" # Mapování portu HOST:KONTEJNER [cite: 25, 64]
    extra_hosts:
      - [cite_start]"host.docker.internal:host-gateway" # Umožní kontejneru vidět Ollamu na tvém PC [cite: 17, 66]
    restart: always